### ISSUE TITLE
Latest jquery 

### ISSUE THREAD

**Issue by hadiswaleh** [liabru/jquery-match-height#175]
jquery-match-height not working with latest jquery min file ie 3.3.1

**Comment by BTS-Chad** [comment]
Did you find a solution to this?

**Comment by MichaelEugeneYuen** [comment]
I have no issue using jquery-match-height with this version

https://code.jquery.com/jquery-3.3.1.min.js

**Comment by liabru** [comment]
Can you provide more information on what is not working, any console errors and in which browsers?

**Comment by RYJASM** [comment]
TypeError: $(...).matchHeight is not a function

All browsers. There seems to be a problem with how the library is declared.
